import unittest
from unittest import mock
import hw04a_ziangLin as client
class TestHw04a(unittest.TestCase):
    def test_notfound_input(self):
        no_content = {
                "message": "Not Found",
                "documentation_url": "https://developer.github.com/v3/repos/#list-user-repositories"}
        repo_list = mock.Mock(return_value=no_content)
        client.send_request = repo_list

        self.assertEqual(client.get_github_repo_commit(' '), 0,
                         msg="api doesn't find a matched user ID, the return value should be 0")

    def test_limit_exceed(self):
        limit_exceed = {
            "message": "API rate limit exceeded for 98.109.30.29. (But here's the good news: Authenticated " \
                       "requests get a higher rate limit. Check out the documentation for more details.)",
            "documentation_url": "https://developer.github.com/v3/repos/#list-user-repositories"}
        repo_list = mock.Mock(return_value=limit_exceed)
        client.send_request = repo_list
        self.assertEqual(client.get_github_repo_commit('daseda'), -1,
                         msg="API rate limit exceeded")


    def test_return_type(self):
        raw_repo_list = [
            {"id": 144656027, "node_id": "MDEwOlJlcG9zaXRvcnkxNDQ2NTYwMjc=", "name": "helloworld",
             "full_name": "richkempinski/helloworld", "private": False,
             "owner": {"login": "richkempinski", "id": 1920366, "node_id": "MDQ6VXNlcjE5MjAzNjY=",
                       "avatar_url": "https://avatars3.githubusercontent.com/u/1920366?v=4", "gravatar_id": "",
                       "url": "https://api.github.com/users/richkempinski",
                       "html_url": "https://github.com/richkempinski",
                       "followers_url": "https://api.github.com/users/richkempinski/followers",
                       "following_url": "https://api.github.com/users/richkempinski/following{/other_user}",
                       "gists_url": "https://api.github.com/users/richkempinski/gists{/gist_id}",
                       "starred_url": "https://api.github.com/users/richkempinski/starred{/owner}{/repo}",
                       "subscriptions_url": "https://api.github.com/users/richkempinski/subscriptions",
                       "organizations_url": "https://api.github.com/users/richkempinski/orgs",
                       "repos_url": "https://api.github.com/users/richkempinski/repos",
                       "events_url": "https://api.github.com/users/richkempinski/events{/privacy}",
                       "received_events_url": "https://api.github.com/users/richkempinski/received_events",
                       "type": "User", "site_admin": False},
             "html_url": "https://github.com/richkempinski/helloworld", "description": "My Hello world repository",
             "fork": False, "url": "https://api.github.com/repos/richkempinski/helloworld",
             "forks_url": "https://api.github.com/repos/richkempinski/helloworld/forks",
             "keys_url": "https://api.github.com/repos/richkempinski/helloworld/keys{/key_id}",
             "collaborators_url": "https://api.github.com/repos/richkempinski/helloworld/collaborators{/collaborator}",
             "teams_url": "https://api.github.com/repos/richkempinski/helloworld/teams",
             "hooks_url": "https://api.github.com/repos/richkempinski/helloworld/hooks",
             "issue_events_url": "https://api.github.com/repos/richkempinski/helloworld/issues/events{/number}",
             "events_url": "https://api.github.com/repos/richkempinski/helloworld/events",
             "assignees_url": "https://api.github.com/repos/richkempinski/helloworld/assignees{/user}",
             "branches_url": "https://api.github.com/repos/richkempinski/helloworld/branches{/branch}",
             "tags_url": "https://api.github.com/repos/richkempinski/helloworld/tags",
             "blobs_url": "https://api.github.com/repos/richkempinski/helloworld/git/blobs{/sha}",
             "git_tags_url": "https://api.github.com/repos/richkempinski/helloworld/git/tags{/sha}",
             "git_refs_url": "https://api.github.com/repos/richkempinski/helloworld/git/refs{/sha}",
             "trees_url": "https://api.github.com/repos/richkempinski/helloworld/git/trees{/sha}",
             "statuses_url": "https://api.github.com/repos/richkempinski/helloworld/statuses/{sha}",
             "languages_url": "https://api.github.com/repos/richkempinski/helloworld/languages",
             "stargazers_url": "https://api.github.com/repos/richkempinski/helloworld/stargazers",
             "contributors_url": "https://api.github.com/repos/richkempinski/helloworld/contributors",
             "subscribers_url": "https://api.github.com/repos/richkempinski/helloworld/subscribers",
             "subscription_url": "https://api.github.com/repos/richkempinski/helloworld/subscription",
             "commits_url": "https://api.github.com/repos/richkempinski/helloworld/commits{/sha}",
             "git_commits_url": "https://api.github.com/repos/richkempinski/helloworld/git/commits{/sha}",
             "comments_url": "https://api.github.com/repos/richkempinski/helloworld/comments{/number}",
             "issue_comment_url": "https://api.github.com/repos/richkempinski/helloworld/issues/comments{/number}",
             "contents_url": "https://api.github.com/repos/richkempinski/helloworld/contents/{+path}",
             "compare_url": "https://api.github.com/repos/richkempinski/helloworld/compare/{base}...{head}",
             "merges_url": "https://api.github.com/repos/richkempinski/helloworld/merges",
             "archive_url": "https://api.github.com/repos/richkempinski/helloworld/{archive_format}{/ref}",
             "downloads_url": "https://api.github.com/repos/richkempinski/helloworld/downloads",
             "issues_url": "https://api.github.com/repos/richkempinski/helloworld/issues{/number}",
             "pulls_url": "https://api.github.com/repos/richkempinski/helloworld/pulls{/number}",
             "milestones_url": "https://api.github.com/repos/richkempinski/helloworld/milestones{/number}",
             "notifications_url": "https://api.github.com/repos/richkempinski/helloworld/notifications{?since,all,participating}",
             "labels_url": "https://api.github.com/repos/richkempinski/helloworld/labels{/name}",
             "releases_url": "https://api.github.com/repos/richkempinski/helloworld/releases{/id}",
             "deployments_url": "https://api.github.com/repos/richkempinski/helloworld/deployments",
             "created_at": "2018-08-14T02:06:43Z", "updated_at": "2018-10-04T17:46:51Z",
             "pushed_at": "2018-10-04T17:46:50Z", "git_url": "git://github.com/richkempinski/helloworld.git",
             "ssh_url": "git@github.com:richkempinski/helloworld.git",
             "clone_url": "https://github.com/richkempinski/helloworld.git",
             "svn_url": "https://github.com/richkempinski/helloworld", "homepage": None, "size": 4,
             "stargazers_count": 0, "watchers_count": 0, "language": "Python", "has_issues": None,
             "has_projects": None, "has_downloads": None, "has_wiki": None, "has_pages": None, "forks_count": 0,
             "mirror_url": None, "archived": None, "open_issues_count": 0, "license": None, "forks": 0,
             "open_issues": 0, "watchers": 0, "default_branch": "master"
             }
        ]
        raw_commit_list = [
            {"sha": "4f47bf9a786c288463670f30d42277ca233c88ad",
             "node_id": "MDY6Q29tbWl0MTQ0NjU2MDI3OjRmNDdiZjlhNzg2YzI4ODQ2MzY3MGYzMGQ0MjI3N2NhMjMzYzg4YWQ=", "commit": {
                "author": {"name": "RichK", "email": "1920366+richkempinski@users.noreply.github.com",
                           "date": "2018-10-04T17:46:49Z"},
                "committer": {"name": "GitHub", "email": "noreply@github.com", "date": "2018-10-04T17:46:49Z"},
                "message": "Update README.md", "tree": {"sha": "c2feae95fc1259d39b06befc8f99537504678bff",
                                                        "url": "https://api.github.com/repos/richkempinski/helloworld/git/trees/c2feae95fc1259d39b06befc8f99537504678bff"},
                "url": "https://api.github.com/repos/richkempinski/helloworld/git/commits/4f47bf9a786c288463670f30d42277ca233c88ad",
                "comment_count": 0, "verification": {"verified": True, "reason": "valid",
                                                     "signature": "-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJbtlIJCRBK7hj4Ov3rIwAAdHIIAJmsqpnhc68G6fEBeA/eLz2g\nlC3ZVjxpnii7UdSft8JhUYr2TEoCh3EDdijrl6Wl26zZUYH5HueDmkLrPGRPxchf\nJvAeLkrNaGfYQ84zcIqp5Z+8VdzdXTBooDyyr2C50Xi2P+NUR5Xq7i0xDWJ2cNKn\npEt8hNYWfyjMW/l2YA7L1WkUcE1q0FzP6fkeQdBJm3XdVAU30KWCir9/eQR0KJFX\nFt48FcK9HT4kxcM+0r4oBthyAktopUTcu5h/0dwc1wn0Vzn6bHEPfrhT0xhwFoOo\nk6SvkifwPrhKRKHhRow+EQP/hYX41FjSbmaUXYkDKJg6wCnGQpWmUxmy/H2jM+A=\n=bWmL\n-----END PGP SIGNATURE-----\n",
                                                     "payload": "tree c2feae95fc1259d39b06befc8f99537504678bff\nparent d0e5316787ce21e176391c46df7513db32d02965\nauthor RichK <1920366+richkempinski@users.noreply.github.com> 1538675209 -0400\ncommitter GitHub <noreply@github.com> 1538675209 -0400\n\nUpdate README.md"}},
             "url": "https://api.github.com/repos/richkempinski/helloworld/commits/4f47bf9a786c288463670f30d42277ca233c88ad",
             "html_url": "https://github.com/richkempinski/helloworld/commit/4f47bf9a786c288463670f30d42277ca233c88ad",
             "comments_url": "https://api.github.com/repos/richkempinski/helloworld/commits/4f47bf9a786c288463670f30d42277ca233c88ad/comments",
             "author": {"login": "richkempinski", "id": 1920366, "node_id": "MDQ6VXNlcjE5MjAzNjY=",
                        "avatar_url": "https://avatars3.githubusercontent.com/u/1920366?v=4", "gravatar_id": "",
                        "url": "https://api.github.com/users/richkempinski",
                        "html_url": "https://github.com/richkempinski",
                        "followers_url": "https://api.github.com/users/richkempinski/followers",
                        "following_url": "https://api.github.com/users/richkempinski/following{/other_user}",
                        "gists_url": "https://api.github.com/users/richkempinski/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/richkempinski/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/richkempinski/subscriptions",
                        "organizations_url": "https://api.github.com/users/richkempinski/orgs",
                        "repos_url": "https://api.github.com/users/richkempinski/repos",
                        "events_url": "https://api.github.com/users/richkempinski/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/richkempinski/received_events",
                        "type": "User", "site_admin": False},
             "committer": {"login": "web-flow", "id": 19864447, "node_id": "MDQ6VXNlcjE5ODY0NDQ3",
                           "avatar_url": "https://avatars3.githubusercontent.com/u/19864447?v=4", "gravatar_id": "",
                           "url": "https://api.github.com/users/web-flow", "html_url": "https://github.com/web-flow",
                           "followers_url": "https://api.github.com/users/web-flow/followers",
                           "following_url": "https://api.github.com/users/web-flow/following{/other_user}",
                           "gists_url": "https://api.github.com/users/web-flow/gists{/gist_id}",
                           "starred_url": "https://api.github.com/users/web-flow/starred{/owner}{/repo}",
                           "subscriptions_url": "https://api.github.com/users/web-flow/subscriptions",
                           "organizations_url": "https://api.github.com/users/web-flow/orgs",
                           "repos_url": "https://api.github.com/users/web-flow/repos",
                           "events_url": "https://api.github.com/users/web-flow/events{/privacy}",
                           "received_events_url": "https://api.github.com/users/web-flow/received_events",
                           "type": "User", "site_admin": False}, "parents": [
                {"sha": "d0e5316787ce21e176391c46df7513db32d02965",
                 "url": "https://api.github.com/repos/richkempinski/helloworld/commits/d0e5316787ce21e176391c46df7513db32d02965",
                 "html_url": "https://github.com/richkempinski/helloworld/commit/d0e5316787ce21e176391c46df7513db32d02965"}]},
            {"sha": "d0e5316787ce21e176391c46df7513db32d02965",
             "node_id": "MDY6Q29tbWl0MTQ0NjU2MDI3OmQwZTUzMTY3ODdjZTIxZTE3NjM5MWM0NmRmNzUxM2RiMzJkMDI5NjU=", "commit": {
                "author": {"name": "RichK", "email": "1920366+richkempinski@users.noreply.github.com",
                           "date": "2018-10-04T17:44:31Z"},
                "committer": {"name": "GitHub", "email": "noreply@github.com", "date": "2018-10-04T17:44:31Z"},
                "message": "Update README.md", "tree": {"sha": "fdfdd667a4823bd4d5b2f8e0b7c92e524e9b6aef",
                                                        "url": "https://api.github.com/repos/richkempinski/helloworld/git/trees/fdfdd667a4823bd4d5b2f8e0b7c92e524e9b6aef"},
                "url": "https://api.github.com/repos/richkempinski/helloworld/git/commits/d0e5316787ce21e176391c46df7513db32d02965",
                "comment_count": 0, "verification": {"verified": True, "reason": "valid",
                                                     "signature": "-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJbtlF/CRBK7hj4Ov3rIwAAdHIIACd3IfRMYk2lzZl03bSxyfjA\nmg2+unrmxaEYclVycAOBY0kgDeY6iTli3t9MKIVREfgMpf/Rbmr0l0VPLEU3+yqi\nurUEyppo3TL5imNryxqq3SuhlIJCv/DY2mG8dPoHzkdMjtfqUGtlhqTa/rlPXnID\n2qbdxD/VGOkEQboT7K/aYzU9xC33dSr+F3p9BWe0nPzL9AgSJ7UujFXt4rBfhilf\niO8Da8I4xFhSX9ZzzY8HKigqa18N6XqY3EerDxHFbaC8FyLRZjNyuFDhaN16mKPq\n5Ju8NzB1N8JWiSRsalQOkqkvPnOkxQusuHhT3qiy2+9gu4zxPNKChYDGQsvPFBs=\n=Hor3\n-----END PGP SIGNATURE-----\n",
                                                     "payload": "tree fdfdd667a4823bd4d5b2f8e0b7c92e524e9b6aef\nparent a2233f84677056145a57633deb29c9db1572c566\nauthor RichK <1920366+richkempinski@users.noreply.github.com> 1538675071 -0400\ncommitter GitHub <noreply@github.com> 1538675071 -0400\n\nUpdate README.md"}},
             "url": "https://api.github.com/repos/richkempinski/helloworld/commits/d0e5316787ce21e176391c46df7513db32d02965",
             "html_url": "https://github.com/richkempinski/helloworld/commit/d0e5316787ce21e176391c46df7513db32d02965",
             "comments_url": "https://api.github.com/repos/richkempinski/helloworld/commits/d0e5316787ce21e176391c46df7513db32d02965/comments",
             "author": {"login": "richkempinski", "id": 1920366, "node_id": "MDQ6VXNlcjE5MjAzNjY=",
                        "avatar_url": "https://avatars3.githubusercontent.com/u/1920366?v=4", "gravatar_id": "",
                        "url": "https://api.github.com/users/richkempinski",
                        "html_url": "https://github.com/richkempinski",
                        "followers_url": "https://api.github.com/users/richkempinski/followers",
                        "following_url": "https://api.github.com/users/richkempinski/following{/other_user}",
                        "gists_url": "https://api.github.com/users/richkempinski/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/richkempinski/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/richkempinski/subscriptions",
                        "organizations_url": "https://api.github.com/users/richkempinski/orgs",
                        "repos_url": "https://api.github.com/users/richkempinski/repos",
                        "events_url": "https://api.github.com/users/richkempinski/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/richkempinski/received_events",
                        "type": "User", "site_admin": False},
             "committer": {"login": "web-flow", "id": 19864447, "node_id": "MDQ6VXNlcjE5ODY0NDQ3",
                           "avatar_url": "https://avatars3.githubusercontent.com/u/19864447?v=4", "gravatar_id": "",
                           "url": "https://api.github.com/users/web-flow", "html_url": "https://github.com/web-flow",
                           "followers_url": "https://api.github.com/users/web-flow/followers",
                           "following_url": "https://api.github.com/users/web-flow/following{/other_user}",
                           "gists_url": "https://api.github.com/users/web-flow/gists{/gist_id}",
                           "starred_url": "https://api.github.com/users/web-flow/starred{/owner}{/repo}",
                           "subscriptions_url": "https://api.github.com/users/web-flow/subscriptions",
                           "organizations_url": "https://api.github.com/users/web-flow/orgs",
                           "repos_url": "https://api.github.com/users/web-flow/repos",
                           "events_url": "https://api.github.com/users/web-flow/events{/privacy}",
                           "received_events_url": "https://api.github.com/users/web-flow/received_events",
                           "type": "User", "site_admin": False}, "parents": [
                {"sha": "a2233f84677056145a57633deb29c9db1572c566",
                 "url": "https://api.github.com/repos/richkempinski/helloworld/commits/a2233f84677056145a57633deb29c9db1572c566",
                 "html_url": "https://github.com/richkempinski/helloworld/commit/a2233f84677056145a57633deb29c9db1572c566"}]},
            {"sha": "a2233f84677056145a57633deb29c9db1572c566",
             "node_id": "MDY6Q29tbWl0MTQ0NjU2MDI3OmEyMjMzZjg0Njc3MDU2MTQ1YTU3NjMzZGViMjljOWRiMTU3MmM1NjY=", "commit": {
                "author": {"name": "RichK", "email": "1920366+richkempinski@users.noreply.github.com",
                           "date": "2018-10-04T17:39:46Z"},
                "committer": {"name": "GitHub", "email": "noreply@github.com", "date": "2018-10-04T17:39:46Z"},
                "message": "Create TestHello.py", "tree": {"sha": "a037fa565ef17271adc78c1d09ef8131fc54fe4f",
                                                           "url": "https://api.github.com/repos/richkempinski/helloworld/git/trees/a037fa565ef17271adc78c1d09ef8131fc54fe4f"},
                "url": "https://api.github.com/repos/richkempinski/helloworld/git/commits/a2233f84677056145a57633deb29c9db1572c566",
                "comment_count": 0, "verification": {"verified": True, "reason": "valid",
                                                     "signature": "-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJbtlBiCRBK7hj4Ov3rIwAAdHIIALHIFmWrttxkLPWZQr9KerUf\nKN0v7SmtQtNH6vMuU3i80eVJzFGICsQZgInPhp2nL1wNYBJ4Zb1gkU4usudea+Dz\nEh4BX20erO2MoNWAbBfC2mMjli/iV8AR4PN+boSz36M23KSGC+2YZD9MMHL1L9Pz\nlYM/Ec9qFbB4+fr4GY1iOWFqXfgG2C00gRYM9jw7UF99lqcozg9nokwaN1vOYp5U\ngdJOZS2LzJTr1XwzE88T0j8bdGN/nrmOPIkMMxbqaY/EKV77XspqQsXh/T8Kkn5s\nFYhAHnIVb1Xw2HTFOxfJPRyCxqQbODqSJxL1eCdVccX4dED5hBhFySdm6NI8tKg=\n=NZPM\n-----END PGP SIGNATURE-----\n",
                                                     "payload": "tree a037fa565ef17271adc78c1d09ef8131fc54fe4f\nparent 1f5f0b2e118d435dd6c7975f38d3a0d45a59ce70\nauthor RichK <1920366+richkempinski@users.noreply.github.com> 1538674786 -0400\ncommitter GitHub <noreply@github.com> 1538674786 -0400\n\nCreate TestHello.py"}},
             "url": "https://api.github.com/repos/richkempinski/helloworld/commits/a2233f84677056145a57633deb29c9db1572c566",
             "html_url": "https://github.com/richkempinski/helloworld/commit/a2233f84677056145a57633deb29c9db1572c566",
             "comments_url": "https://api.github.com/repos/richkempinski/helloworld/commits/a2233f84677056145a57633deb29c9db1572c566/comments",
             "author": {"login": "richkempinski", "id": 1920366, "node_id": "MDQ6VXNlcjE5MjAzNjY=",
                        "avatar_url": "https://avatars3.githubusercontent.com/u/1920366?v=4", "gravatar_id": "",
                        "url": "https://api.github.com/users/richkempinski",
                        "html_url": "https://github.com/richkempinski",
                        "followers_url": "https://api.github.com/users/richkempinski/followers",
                        "following_url": "https://api.github.com/users/richkempinski/following{/other_user}",
                        "gists_url": "https://api.github.com/users/richkempinski/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/richkempinski/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/richkempinski/subscriptions",
                        "organizations_url": "https://api.github.com/users/richkempinski/orgs",
                        "repos_url": "https://api.github.com/users/richkempinski/repos",
                        "events_url": "https://api.github.com/users/richkempinski/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/richkempinski/received_events",
                        "type": "User", "site_admin": False},
             "committer": {"login": "web-flow", "id": 19864447, "node_id": "MDQ6VXNlcjE5ODY0NDQ3",
                           "avatar_url": "https://avatars3.githubusercontent.com/u/19864447?v=4", "gravatar_id": "",
                           "url": "https://api.github.com/users/web-flow", "html_url": "https://github.com/web-flow",
                           "followers_url": "https://api.github.com/users/web-flow/followers",
                           "following_url": "https://api.github.com/users/web-flow/following{/other_user}",
                           "gists_url": "https://api.github.com/users/web-flow/gists{/gist_id}",
                           "starred_url": "https://api.github.com/users/web-flow/starred{/owner}{/repo}",
                           "subscriptions_url": "https://api.github.com/users/web-flow/subscriptions",
                           "organizations_url": "https://api.github.com/users/web-flow/orgs",
                           "repos_url": "https://api.github.com/users/web-flow/repos",
                           "events_url": "https://api.github.com/users/web-flow/events{/privacy}",
                           "received_events_url": "https://api.github.com/users/web-flow/received_events",
                           "type": "User", "site_admin": False}, "parents": [
                {"sha": "1f5f0b2e118d435dd6c7975f38d3a0d45a59ce70",
                 "url": "https://api.github.com/repos/richkempinski/helloworld/commits/1f5f0b2e118d435dd6c7975f38d3a0d45a59ce70",
                 "html_url": "https://github.com/richkempinski/helloworld/commit/1f5f0b2e118d435dd6c7975f38d3a0d45a59ce70"}]},
            {"sha": "1f5f0b2e118d435dd6c7975f38d3a0d45a59ce70",
             "node_id": "MDY6Q29tbWl0MTQ0NjU2MDI3OjFmNWYwYjJlMTE4ZDQzNWRkNmM3OTc1ZjM4ZDNhMGQ0NWE1OWNlNzA=", "commit": {
                "author": {"name": "RichK", "email": "1920366+richkempinski@users.noreply.github.com",
                           "date": "2018-10-04T17:37:06Z"},
                "committer": {"name": "GitHub", "email": "noreply@github.com", "date": "2018-10-04T17:37:06Z"},
                "message": "Create .travis.yml", "tree": {"sha": "3d57cbcf8ef5fdfce3330e94f954d3aa23a2fd0b",
                                                          "url": "https://api.github.com/repos/richkempinski/helloworld/git/trees/3d57cbcf8ef5fdfce3330e94f954d3aa23a2fd0b"},
                "url": "https://api.github.com/repos/richkempinski/helloworld/git/commits/1f5f0b2e118d435dd6c7975f38d3a0d45a59ce70",
                "comment_count": 0, "verification": {"verified": True, "reason": "valid",
                                                     "signature": "-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJbtk/CCRBK7hj4Ov3rIwAAdHIIAK/ZGwx4Hz3OsFd8Ua4sfxye\nPu+KvzAcEo6pBRNqE6AFSPQP/xDDV31eBs4d9owM5+j92K+XMrMhEa7WeMiteiaa\n5mR4T6zIqna4wMKIE9/7jGcqzjnmHEvvqyyP7qhzOq/zPOLahXEc0a30q9mO/qUg\n/8YSmTDlWMiztSRGWX9vEjsbIZ1FcmKT4YiUrtb3XZN1UamOk9/HyHSJij3XriEQ\nnToZaSTgkhisEESk6qY/idUxsVycIivujErrCPv2LOwvwP0bl7saUpCN29G/x35d\nsXqXADMljqUOGUYFMzLxikLLCJUDyUu7DYxkitKDhn2YmHZAbH6mPZyuvtG32c8=\n=BgcI\n-----END PGP SIGNATURE-----\n",
                                                     "payload": "tree 3d57cbcf8ef5fdfce3330e94f954d3aa23a2fd0b\nparent 7e436e6c4003cb1c821a6b719806445a741dda71\nauthor RichK <1920366+richkempinski@users.noreply.github.com> 1538674626 -0400\ncommitter GitHub <noreply@github.com> 1538674626 -0400\n\nCreate .travis.yml"}},
             "url": "https://api.github.com/repos/richkempinski/helloworld/commits/1f5f0b2e118d435dd6c7975f38d3a0d45a59ce70",
             "html_url": "https://github.com/richkempinski/helloworld/commit/1f5f0b2e118d435dd6c7975f38d3a0d45a59ce70",
             "comments_url": "https://api.github.com/repos/richkempinski/helloworld/commits/1f5f0b2e118d435dd6c7975f38d3a0d45a59ce70/comments",
             "author": {"login": "richkempinski", "id": 1920366, "node_id": "MDQ6VXNlcjE5MjAzNjY=",
                        "avatar_url": "https://avatars3.githubusercontent.com/u/1920366?v=4", "gravatar_id": "",
                        "url": "https://api.github.com/users/richkempinski",
                        "html_url": "https://github.com/richkempinski",
                        "followers_url": "https://api.github.com/users/richkempinski/followers",
                        "following_url": "https://api.github.com/users/richkempinski/following{/other_user}",
                        "gists_url": "https://api.github.com/users/richkempinski/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/richkempinski/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/richkempinski/subscriptions",
                        "organizations_url": "https://api.github.com/users/richkempinski/orgs",
                        "repos_url": "https://api.github.com/users/richkempinski/repos",
                        "events_url": "https://api.github.com/users/richkempinski/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/richkempinski/received_events",
                        "type": "User", "site_admin": False},
             "committer": {"login": "web-flow", "id": 19864447, "node_id": "MDQ6VXNlcjE5ODY0NDQ3",
                           "avatar_url": "https://avatars3.githubusercontent.com/u/19864447?v=4", "gravatar_id": "",
                           "url": "https://api.github.com/users/web-flow", "html_url": "https://github.com/web-flow",
                           "followers_url": "https://api.github.com/users/web-flow/followers",
                           "following_url": "https://api.github.com/users/web-flow/following{/other_user}",
                           "gists_url": "https://api.github.com/users/web-flow/gists{/gist_id}",
                           "starred_url": "https://api.github.com/users/web-flow/starred{/owner}{/repo}",
                           "subscriptions_url": "https://api.github.com/users/web-flow/subscriptions",
                           "organizations_url": "https://api.github.com/users/web-flow/orgs",
                           "repos_url": "https://api.github.com/users/web-flow/repos",
                           "events_url": "https://api.github.com/users/web-flow/events{/privacy}",
                           "received_events_url": "https://api.github.com/users/web-flow/received_events",
                           "type": "User", "site_admin": False}, "parents": [
                {"sha": "7e436e6c4003cb1c821a6b719806445a741dda71",
                 "url": "https://api.github.com/repos/richkempinski/helloworld/commits/7e436e6c4003cb1c821a6b719806445a741dda71",
                 "html_url": "https://github.com/richkempinski/helloworld/commit/7e436e6c4003cb1c821a6b719806445a741dda71"}]}
        ]
        repo_list = mock.Mock(return_value=raw_repo_list)
        commit_list = mock.Mock(return_value=raw_commit_list)
        client.send_request = repo_list
        client.get_repo_commit = commit_list
        self.assertEqual(type(client.get_github_repo_commit('richkempinski')), list,
                         msg='If enter a valid parameter, it suppose to return a list type value')
        self.assertEqual(type(client.get_github_repo_commit('richkempinski')[0]), str,
                         msg='Items in the list suppose to be string format')
        self.assertEqual(client.get_github_repo_commit('richkempinski')[0], 'Repo: helloworld Number of commits: 4',
                         msg="The item display should be 'Repo:... Number of commits:...'")
if __name__ == '__main__':
    unittest.main()